/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.view.MainViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainviewport',

    requires: [
        'LanistaTrainer.view.MainViewportViewModel',
        'LanistaTrainer.view.MyView',
        'Ext.XTemplate',
        'Ext.tab.Panel',
        'Ext.view.View',
        'Ext.tab.Tab',
        'Ext.tab.Bar',
        'Ext.form.Label'
    ],

    viewModel: {
        type: 'mainviewport'
    },
    id: 'mainViewport',
    layout: 'fit',
    defaultListenerScope: true,

    listeners: {
        resize: 'onViewportResize',
        afterrender: 'onViewportAfterRender'
    },

    initConfig: function(instanceConfig) {
        var me = this,
            config = {
                items: [
                    {
                        xtype: 'component',
                        height: 150,
                        id: 'header',
                        itemId: 'header',
                        maxHeight: 100,
                        style: 'z-index:1; background-color: rgba(227,227,227,0.7)',
                        tpl: [
                            '    <div class=header-I>',
                            '        <div class="header-logo"> p </div>',
                            '        <div class="header-text-lanista"> Lanista </div>',
                            '        <div class="header-title">{title}</div>',
                            '    </div>        ',
                            '    <div class="header-info">{info}</div>'
                        ]
                    },
                    {
                        xtype: 'container',
                        id: 'lanistaStage',
                        itemId: 'lanistaStage',
                        style: 'top:0!important;position: absolute;z-index:1;',
                        width: 150,
                        layout: {
                            type: 'hbox',
                            align: 'stretch',
                            pack: 'center'
                        },
                        items: [
                            {
                                xtype: 'panel',
                                border: false,
                                cls: 'lanista-command-panel',
                                id: 'leftCommandPanel',
                                itemId: 'leftCommandPanel',
                                style: 'margin-top:100px;',
                                width: 88,
                                animCollapse: true,
                                collapseDirection: 'right',
                                collapsed: false,
                                header: false,
                                manageHeight: false,
                                titleCollapse: true,
                                layout: {
                                    type: 'vbox',
                                    align: 'center',
                                    pack: 'center'
                                }
                            },
                            {
                                xtype: 'container',
                                flex: 1,
                                border: false,
                                id: 'mainStage',
                                itemId: 'mainStage',
                                layout: 'card',
                                items: [
                                    {
                                        xtype: 'panel',
                                        border: false,
                                        cls: 'lanista-plan-panel',
                                        id: 'planPanel',
                                        itemId: 'planPanel',
                                        width: 400,
                                        items: [
                                            {
                                                xtype: 'panel',
                                                border: false,
                                                cls: 'lanista-headerplan-panel',
                                                height: 181,
                                                id: 'planHeader',
                                                itemId: 'planHeader',
                                                margin: '100 0 0 0',
                                                tpl: [
                                                    '<div class="plan-header-description" id="planHeaderDescription">{description}</div>',
                                                    '<div class="plan-header-info" id="planHeaderInfoBu">',
                                                    '    <div class="plan-createddate-info">',
                                                    '        <div class="plan-header-attribute">{[Ext.ux.LanguageManager.TranslationArray.CREATED_AT]}:</div><div class="plan-header-value">{[Ext.Date.format ( values.creation_date, \'d, M Y\' )]}</div>',
                                                    '    </div>',
                                                    '    <div class="plan-created-info">    ',
                                                    '        <div class="plan-header-attribute">{[values.bu_name !== "" ? Ext.ux.LanguageManager.TranslationArray.PLAN_FROM_GYM : Ext.ux.LanguageManager.TranslationArray.PLAN_FROM_TRAINER]}:</div><div class="plan-header-value" id="planHeaderValue">{creator_name}</div>',
                                                    '    </div>',
                                                    '    <div class="dashboard-customer-background" style="customer-image">a</div>',
                                                    '    <div class="plan-header-customer-info" style="background-image: url({[ values.bu_name !== "" ? \'http://lanista-training.com/app/\' + values.bu_domain + \'/logo.png\' :  Ext.ux.ConfigManager.getServer() + Ext.ux.ConfigManager.getRoot() + \'/tpmanager/img/p/\' + values.creator_id + \'_photo.jpg\']});"></div>',
                                                    '    <div class="plan-header-email">{[values.bu_email !== "" ? values.bu_email : ""]}</div>',
                                                    '</div>'
                                                ]
                                            }
                                        ],
                                        dockedItems: [
                                            {
                                                xtype: 'tabpanel',
                                                dock: 'bottom',
                                                border: false,
                                                cls: 'plan-exercises-panel',
                                                id: 'exercicesPanel',
                                                itemId: 'exercicesPanel',
                                                activeTab: 1,
                                                items: [
                                                    me.processD1({
                                                        xtype: 'planexerciseslist',
                                                        id: 'd1',
                                                        itemId: 'd1',
                                                        preserveScrollOnRefresh: true
                                                    }),
                                                    {
                                                        xtype: 'panel',
                                                        hidden: true,
                                                        itemId: 'plus',
                                                        title: '+'
                                                    }
                                                ],
                                                listeners: {
                                                    tabchange: 'onTabpanelTabChange'
                                                },
                                                tabBar: {
                                                    xtype: 'tabbar',
                                                    border: false,
                                                    plain: true
                                                }
                                            }
                                        ]
                                    }
                                ]
                            },
                            {
                                xtype: 'panel',
                                border: false,
                                cls: 'lanista-command-panel',
                                itemId: 'rightCommandPanel',
                                style: 'margin-top:100px;',
                                width: 88,
                                animCollapse: true,
                                collapseDirection: 'right',
                                collapsed: false,
                                header: false,
                                manageHeight: false,
                                titleCollapse: true,
                                layout: {
                                    type: 'vbox',
                                    align: 'center',
                                    pack: 'center'
                                }
                            }
                        ]
                    },
                    {
                        xtype: 'container',
                        cls: 'lanista-copyrights',
                        height: '20px',
                        itemId: 'lanistaCopyRights',
                        items: [
                            {
                                xtype: 'label',
                                cls: 'lanista-copyrights-text',
                                html: '<span>Lanista</span> Trainingssoftware &#169; 2012. All rights reserved.',
                                itemId: 'strCopyRights'
                            }
                        ]
                    }
                ]
            };
        if (instanceConfig) {
            me.getConfigurator().merge(me, config, instanceConfig);
        }
        return me.callParent([config]);
    },

    processD1: function(config) {

        config.title = Ext.ux.LanguageManager.TranslationArray.DAY + ' 1';

        return config;
    },

    onTabpanelTabChange: function(tabPanel, newCard, oldCard, eOpts) {
        //var tapPanelSize = tabPanel.items.getCount(),
        //var   controller = LanistaTrainer.app.getController ('PlanController');

        /*if (tabPanel.activeTab.title === '+') {
            if ( tapPanelSize  < 9 ) {
                tabPanel.insert( tapPanelSize -1 , {
                    xtype: 'planExercisesList',
                    id: 'd'+(tapPanelSize),
                    title: Ext.ux.LanguageManager.TranslationArray.DAY + ' ' + (tapPanelSize),
                    store: controller.plan.planexercises()
                });
                tabPanel.setActiveTab(tabPanel.items.items[tapPanelSize -1]);
                tabPanel.getActiveTab().getEl().setHeight(tabPanel.getActiveTab().el.dom.clientHeight - 45);
            }
        }
        else{
            tabPanel.setActiveTab(newCard);
            tabPanel.getActiveTab().getEl().setHeight(tabPanel.getActiveTab().el.dom.clientHeight - 45);
        }*/
    },

    onViewportResize: function(component, width, height, oldWidth, oldHeight, eOpts) {
        component.down('#lanistaCopyRights').setY(component.el.dom.clientHeight - 20);

        if (LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getActiveTab().el){
            if (!Ext.getCmp('mainStage')) return;
            LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getActiveTab().getEl().setHeight(component.el.dom.clientHeight - 240);
            LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getEl().setHeight(component.el.dom.clientHeight - 240);

        }

    },

    onViewportAfterRender: function(component, eOpts) {
        var el = component.el;

            component.down('#lanistaCopyRights').setY(component.el.dom.clientHeight - 20);
            if (LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getActiveTab().el){
                if (!Ext.getCmp('mainStage')) return;
                LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getActiveTab().getEl().setHeight(component.el.dom.clientHeight - 240);
                LanistaTrainer.app.getController('PlanController').getPlanPanel().down ('tabpanel').getEl().setHeight(component.el.dom.clientHeight - 240);
            }

            el.on('click',function(e,t) {
                if (component.down('#videoWindow'))
                    component.down('#videoWindow').hide();
            },this,{delegate: '.x-mask'});

    }

});