/*
 * File: app/view/VideoWindow.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.view.VideoWindow', {
    extend: 'Ext.window.Window',
    alias: 'widget.videowindow',

    requires: [
        'LanistaTrainer.view.VideoWindowViewModel'
    ],

    viewModel: {
        type: 'videowindow'
    },
    border: false,
    cls: 'lanista-video-window',
    draggable: false,
    height: 510,
    id: 'videoWindow',
    resizable: false,
    style: 'background: black;',
    width: 800,
    closable: false,
    modal: true,
    defaultListenerScope: true,

    listeners: {
        hide: 'onVideoWindowHide'
    },

    onVideoWindowHide: function(component, eOpts) {
        component.destroy();
    }

});