/*
 * File: app/model/Plan.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('LanistaTrainer.model.Plan', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'id'
        },
        {
            type: 'int',
            name: 'template'
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'int',
            name: 'days'
        },
        {
            type: 'int',
            name: 'duration'
        },
        {
            type: 'string',
            name: 'description'
        },
        {
            type: 'int',
            name: 'customer_id'
        },
        {
            type: 'int',
            name: 'trainer_id'
        },
        {
            type: 'string',
            name: 'creator_name'
        },
        {
            type: 'date',
            name: 'creation_date'
        },
        {
            type: 'date',
            name: 'changed_date'
        },
        {
            type: 'int',
            name: 'category'
        },
        {
            type: 'int',
            name: 'public_template'
        },
        {
            type: 'string',
            name: 'bu_name'
        },
        {
            type: 'string',
            name: 'bu_email'
        },
        {
            type: 'string',
            name: 'bu_domain'
        },
        {
            type: 'string',
            name: 'creator_website'
        }
    ]
});